name: "Docker Build"
description: "Build Docker image with caching"

inputs:
  image-name:
    description: "Name of the Docker image"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build with cache
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ inputs.image-name }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: List images
      shell: bash
      run: docker images