name: "Docker Build"
description: "Builds a Docker image and lists local Docker images"

inputs:
  image-name:
    description: "Name of the Docker image"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build docker image
      shell: bash
      run: docker build -t ${{ inputs.image-name }}:${{ github.sha }} .

    - name: List images
      shell: bash
      run: docker images